# Generated by Django 4.2.2 on 2023-06-13 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hordak', '0037_auto_20230516_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='code',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='code'),
        ),
    ]
